version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:14.04-browsers
    steps:
      - checkout
      - run: java -version
      - run: sudo apt-get install maven
      - run: mvn test
      - run: mvn site
      - store_artifacts:
                path: target/surefire-reports
                destination: tr1
                path: build/reports/tests
                destination: tr2

      -   run:
                name: install dependencies
                command: |
                    wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
                    unzip sonar-scanner-cli-3.2.0.1227-linux.zip
                    chmod +x ./sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner
                    chmod +x ./sonar-scanner-3.2.0.1227-linux/jre/bin/java

      -   run:
                      name: analyze with Sonar
                      command: |
                                          ./sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io