version: 2
jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:14.04-browsers
    steps:
      - checkout
      - run: apt-get install maven
      - run: mvn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test