version: 2
jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:14.04-browsers
    steps:
      - checkout
      - run: java -version
      - run: sudo apt-get install maven3
      - run: mvn test
      - run:
                name: install dependencies
                command: |
                    wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
                    unzip sonar-scanner-cli-3.2.0.1227-linux.zip
                    chmod +x ./sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner
                    chmod +x ./sonar-scanner-3.2.0.1227-linux/jre/bin/java
                    wget https://bintray.com/qameta/generic/download_file?file_path=io%2Fqameta%2Fallure%2Fallure%2F2.7.0%2Fallure-2.7.0.zip -O allure-2.7.0.zip
                    unzip allure-2.7.0.zip
                    chmod +x ./allure-2.7.0/bin/allure
      - run:
            name: generate allure report
            command: mvn allure:report
      - run:
                 name: analyze with Sonar
                 command: |
                                    ./sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io
      - store_artifacts:
                      path: target/
                      destination: tr1
workflows:
  version: 2
  build_and_test:
    jobs:
      - test